name: CI
on: pull_request
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - run: npm ci
      - run: npm run build
      - run: npm test
  # ci-job이 성공/실패하면 그에 해당하는 comment를 닮
  add-comment:
    runs-on: ubuntu-latest
    needs: ci-job # ci-job 종료 이후 add-comment 수행
    if: always() # 결과와 상관 없이 항상 수행
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment to PR (성공)
        if: needs.ci-job.result == 'success'
        uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🟢 CI passed"
            })
      - name: Comment to PR (실패)
        if: needs.ci-job.result == 'failure'
        uses: actions/github-script@v6
        id: my-script2
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "❌ CI failed"
            })
